"""Change customer_profiles.location to Enum and add address field

Revision ID: 809a5ff95ac3
Revises: cb5783ce6599
Create Date: 2025-10-08 02:03:52.633297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '809a5ff95ac3'
down_revision: Union[str, Sequence[str], None] = 'cb5783ce6599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('address', sa.String(length=255), nullable=True))
    op.alter_column('customer_profiles', 'location',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('NORTH', 'SOUTH', 'EAST', 'WEST', 'MID', name='locationenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_profiles', 'location',
               existing_type=sa.Enum('NORTH', 'SOUTH', 'EAST', 'WEST', 'MID', name='locationenum'),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('customer_profiles', 'address')
    # ### end Alembic commands ###
