"""update orders table columns

Revision ID: cb5783ce6599
Revises: 
Create Date: 2025-09-29 21:10:27.743693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb5783ce6599'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_profiles', 'company_name')
    op.add_column('orders', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('location', sa.Enum('NORTH', 'SOUTH', 'EAST', 'WEST', 'MID', name='locationenum'), nullable=False))
    op.add_column('orders', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'location')
    op.drop_column('orders', 'price')
    op.add_column('customer_profiles', sa.Column('company_name', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
