"""Add balance to customer profiles and payment status to orders

Revision ID: f0e76034ca72
Revises: b1f061c3792c
Create Date: 2025-10-09 18:43:14.627078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e76034ca72'
down_revision: Union[str, Sequence[str], None] = 'b1f061c3792c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.Enum('unpaid', 'paid', name='paymentstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.drop_column('customer_profiles', 'balance')
    # ### end Alembic commands ###
